version: "3.7"

services:
  association:
    build: ./association_tourneys_users
    container_name: association
    volumes:
      - type: bind
        source: ./association_tourneys_users/
        target: /src
    environment:
      - APP_NAME:association_api

  tourneycrud:
    build: ./tournaments_crud
    container_name: tournaments_crud
    volumes:
      - type: bind
        source: ./tournaments_crud/
        target: /src
    environment:
      - APP_NAME:tourney_crud_api

  usercrud:
    build: ./users_crud
    container_name: users_crud
    volumes:
      - type: bind
        source: ./users_crud/
        target: /src
    environment:
      - APP_NAME=users_crud_api

  vuedisplay:
    build: ./display
    container_name: vue_display
    depends_on:
      - apigateway
      - association
      - tourneycrud
      - usercrud
    ports:
      - 8080:80
    restart: on-failure
    volumes:
      - "./display:/app"
    environment:
      - APP_NAME=vue_display_api

  apigateway:
    image: nginx:1.17.10
    container_name: api_gateway
    depends_on:
      - association
      - tourneycrud
      - usercrud
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
