server {

    listen 80;

    location /assoc {
        include uwsgi_params;
        uwsgi_pass association:5000;
    }

    location /users {
        include uwsgi_params;
        uwsgi_pass users_crud:5000;
    }

    location /tourneys {
        include uwsgi_params;
        uwsgi_pass tournaments_crud:5000;
    }

}

