# PVC ask for resources
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
